In [1]:
from vod.configuration import KittiLocations
from pathlib import Path
from vod.frame import FrameDataLoader, FrameTransformMatrix
from os import listdir
from vod.frame import transform_pcl
import numpy as np
from tqdm import tqdm
from helper import paths, write_pointcloud, load_original_radar_pointcloud, load_transformed_radar_pointcloud

# Create a paths.py in the helper dir containing a dict with the path name to the data set (or directly use a string)
ROOT_PATH = Path(paths["DELFT_DATASET"])
RADAR_PATH = ROOT_PATH / "radar" / "training"
OUTPUT_PATH = RADAR_PATH / "velodyne_transformed_to_lidar"
OUTPUT_PATH.mkdir(exist_ok=True) # Creates the output dir for the transformed radar data

In [2]:
# Load paths, check if they are correct
kitti_locations = KittiLocations(root_dir=ROOT_PATH,
                                            output_dir="",
                                            frame_set_path="",
                                            pred_dir="",
                                            )

print(f"Foggy lidar dir: {kitti_locations.lidar_dir}")
print(f"Foggy radar dir: {kitti_locations.radar_dir}")

Foggy lidar dir: /run/media/tarexo/RWU_IKI_ELSER_ST/yasin/thesis/datasets/delft_VoD/view_of_delft_PUBLIC/lidar/training/velodyne
Foggy radar dir: /run/media/tarexo/RWU_IKI_ELSER_ST/yasin/thesis/datasets/delft_VoD/view_of_delft_PUBLIC/radar/training/velodyne


In [3]:
# Get file list from radar dir
file_list = listdir(kitti_locations.radar_dir)

In [4]:
# Load radar pc, transform it into the velodyne coordinate system and save it to OUTPUT_PATH
for file_name in tqdm(file_list):
    frame_data = FrameDataLoader(kitti_locations=kitti_locations, frame_number=file_name[:-4])
    transforms = FrameTransformMatrix(frame_data)
    transformed_pc = transform_pcl(frame_data.radar_data, transforms.t_lidar_radar)
    print(transformed_pc[-1])
    # write_pointcloud(transformed_pc, OUTPUT_PATH, file_name)

  0%|          | 0/8682 [00:00<?, ?it/s]

  2%|▏         | 132/8682 [00:00<00:13, 655.72it/s]

[80.41362762 -4.50382376 -4.97898912  1.        ]
[79.97000122 37.28981018 18.45565414  1.        ]
[95.86707306 11.06103325  3.27909708  1.        ]
[97.12149811  2.57091045 -3.16276455  1.        ]
[58.12020111 10.70301247  5.79970217  1.        ]
[ 89.03775787 -41.42694473  -1.39087403   1.        ]
[92.41175842  1.9185884  -0.30299202  1.        ]
[ 72.27672577 -43.72633743  -1.11001623   1.        ]
[85.21609497 44.2177124   2.59969306  1.        ]
[96.47098541 11.61937618 -2.47647524  1.        ]
[97.58970642  6.24240303 -1.38348341  1.        ]
[97.82534027 -5.38509178 -7.79453611  1.        ]
[96.84301758 -7.27294302 -4.00722933  1.        ]
[97.67611694 -1.1057092  -0.8813991   1.        ]
[96.81406403 -8.62085342  7.15859652  1.        ]
[96.93781281  1.83399391 -4.18824768  1.        ]
[96.11739349 -4.7989397  -8.99092674  1.        ]
[83.84013367 -9.18576336 -2.80729222  1.        ]
[83.67920685 -2.29958153  6.16633844  1.        ]
[ 84.64454651   0.72224975 -18.31511879   

  3%|▎         | 275/8682 [00:00<00:12, 695.75it/s]

[92.42855835 28.66165352  3.62497258  1.        ]
[ 96.10505676 -10.42228985  -0.33741668   1.        ]
[94.53366852 17.38148308 -9.50004387  1.        ]
[96.79808807 -0.9104656  -3.40791774  1.        ]
[95.3106308  10.29216862 -8.25063038  1.        ]
[95.89955139 14.70516777 -7.82950783  1.        ]
[93.47331238  1.99416816 -0.39275289  1.        ]
[94.77246094  1.21425498 -2.57861614  1.        ]
[95.76676941 -0.90431529 11.52782822  1.        ]
[ 41.68634415 -24.72891426   5.16186714   1.        ]
[9.43072128e+01 2.51344528e+01 7.42621049e-02 1.00000000e+00]
[91.00867462  4.96212244  6.80956554  1.        ]
[65.42536926 17.41454315  2.13070893  1.        ]
[94.71955872 28.31584358 -5.99166489  1.        ]
[96.44392395 -9.17458439  6.34466839  1.        ]
[ 88.83735657 -23.3475666   -2.23262811   1.        ]
[87.89647675  1.46616411 -3.96386385  1.        ]
[78.22270203 27.68567848  1.18254948  1.        ]
[96.5708313   7.1928134  -2.22851348  1.        ]
[85.0111618  16.39262199  

  5%|▍         | 418/8682 [00:00<00:11, 699.78it/s]

[61.68737411 14.02198792  0.75104129  1.        ]
[94.42735291  1.56407583  2.31888509  1.        ]
[96.71092224  6.09645319  5.66767836  1.        ]
[97.48075867  0.34786212 -4.76836538  1.        ]
[96.99713898 -1.02166092 -2.01158595  1.        ]
[ 9.77507706e+01  2.80845070e+00 -2.01643561e-03  1.00000000e+00]
[94.67488098 15.14810085  1.17549753  1.        ]
[38.64573288 59.31603241 -0.89167428  1.        ]
[43.05674362 38.95599747 -0.10557278  1.        ]
[95.72947693  5.36079311  7.81898499  1.        ]
[ 89.0215683  -36.77688217  12.05888081   1.        ]
[93.59194183 26.8918972   2.64436626  1.        ]
[96.37838745 -3.4737227  -6.37680435  1.        ]
[90.26094055  6.00686789  5.38829756  1.        ]
[76.22564697 -6.9605279  -7.62375164  1.        ]
[98.32841492 -6.0437088  -0.92605913  1.        ]
[23.77039528  2.33011174  2.45728922  1.        ]
[92.05543518 -1.7556392  -1.12978065  1.        ]
[96.75807953  7.69214106 -6.21646261  1.        ]
[96.47063446 -0.64329016 -1.88

  5%|▍         | 433/8682 [00:00<00:11, 690.36it/s]


[94.49384308 -7.25932264 -3.52121687  1.        ]
[94.30135345 19.97517204  1.08920968  1.        ]
[97.10749817 -6.33422089 -2.19523454  1.        ]
[96.50289917 -2.95465374 -5.66684675  1.        ]
[97.43703461 -0.46770748 -1.87973905  1.        ]
[ 94.84724426 -15.31974888   6.4569025    1.        ]
[ 96.86154175 -11.63404846  -3.09204006   1.        ]
[97.68334198 -2.80824614 -8.6328907   1.        ]
[78.39391327 -2.36103034 -1.49167264  1.        ]
[ 9.75173798e+01 -3.09050345e+00 -1.82035365e-04  1.00000000e+00]
[ 81.44232178 -33.41305923   3.81682658   1.        ]


KeyboardInterrupt: 